//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSVPSeminarsWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MemberIsReport
    {
        public string Name { get; set; }
        public string LastName { get; set; }
        public string NameReport { get; set; }
        public string Annotation { get; set; }
    }
}
