//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPerformanceWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WorseStudents
    {
        public string Email { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> BasicsProgramingСourse { get; set; }
        public Nullable<byte> C_Сourse { get; set; }
        public Nullable<byte> AspNetСourse { get; set; }
        public Nullable<byte> AdoNetСourse { get; set; }
        public Nullable<byte> JavaСourse { get; set; }
        public Nullable<byte> PythonСourse { get; set; }
        public Nullable<byte> WebСourse { get; set; }
        public Nullable<decimal> FinalGrade { get; set; }
    }
}
